CREATE sequence hibernate_sequence start 1 increment 1;

CREATE TABLE message (
  ID int8 NOT NULL,
  FILENAME VARCHAR(255),
  TAG VARCHAR(255),
  TEXT VARCHAR(2048) NOT NULL,
  USER_ID int8,
  PRIMARY KEY (ID)
);

CREATE TABLE user_role (
  USER_ID int8 NOT NULL,
  ROLES VARCHAR(255)
);

CREATE TABLE usr (
  ID int8 NOT NULL,
  ACTIVATION_CODE VARCHAR(255),
  ACTIVE boolean NOT NULL,
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE if EXISTS message
  ADD CONSTRAINT message_user_fk
  FOREIGN KEY (user_id) REFERENCES usr;

ALTER TABLE if EXISTS user_role
  ADD CONSTRAINT user_role_fk
  FOREIGN KEY (user_id) REFERENCES usr;
